version: "3"
services:
  client-api-service:
    depends_on: [zs-mongo]
    image: cas:local
    container_name: client-api-service
    ports:
      - 8080:8080
    environment:
      - REST_PORT=8080
      - INPUT_PORTS_FILE=/build/ports.json
      - PORT_DOMAIN_SERVICE_API=port-domain-service:8090

  port-domain-service:
    depends_on: [client-api-service]
    image: pds:local
    container_name: port-domain-service
    ports:
      - 8090:8090
    environment:
      - GRPC_PORT=8090
      - MONGO=mongodb://zs-mongo:27017

  users:
    depends_on: [ zs-mongo ]
    image: users:local
    container_name: users
    ports:
      - 9999:8080
      - 10000:8090
    environment:
      - REST_PORT=8080
      - GRPC_PORT=8090
      - MONGO=mongodb://zs-mongo:27017

  validation-service:
    depends_on: [ zs-mongo ]
    image: validationsvc:local
    container_name: validation-service
    ports:
      - 11000:8080
    environment:
      - REST_PORT=8080
      - MONGO=mongodb://zs-mongo:27017

  zs-mongo:
    container_name: zs-mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]